"""document add node

Revision ID: 0db008c8290a
Revises: 8037426eb92d
Create Date: 2025-12-05 22:56:17.611723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db008c8290a'
down_revision: Union[str, Sequence[str], None] = '8037426eb92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('wiki_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'node', 'wiki', ['wiki_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.drop_column('node', 'wiki_id')
    # ### end Alembic commands ###
