"""restore model relationship

Revision ID: 31f33e04484c
Revises: 4c23a61c0fe8
Create Date: 2025-07-22 14:52:22.815703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f33e04484c'
down_revision: Union[str, Sequence[str], None] = '4c23a61c0fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'model', 'model_provider', ['model_provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model', type_='foreignkey')
    # ### end Alembic commands ###
