"""add tenant model_provider join

Revision ID: 36aed46491ad
Revises: f29e2f40bd8f
Create Date: 2025-07-24 18:35:52.659047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36aed46491ad'
down_revision: Union[str, Sequence[str], None] = 'f29e2f40bd8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_provider_tenant_join',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('model_provider_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_provider_id'], ['model_provider.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='model_provider_tenant_join_pkey'),
    sa.UniqueConstraint('tenant_id', 'model_provider_id', name='unique_model_provider_tenant_join')
    )
    op.create_index('model_provider_tenant_join_model_provider_id_idx', 'model_provider_tenant_join', ['model_provider_id'], unique=False)
    op.create_index('model_provider_tenant_join_tenant_id_idx', 'model_provider_tenant_join', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('model_provider_tenant_join_tenant_id_idx', table_name='model_provider_tenant_join')
    op.drop_index('model_provider_tenant_join_model_provider_id_idx', table_name='model_provider_tenant_join')
    op.drop_table('model_provider_tenant_join')
    # ### end Alembic commands ###
