"""update conversation message

Revision ID: 414364b6daa2
Revises: 217fb669225a
Create Date: 2025-11-02 12:54:08.312603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414364b6daa2'
down_revision: Union[str, Sequence[str], None] = '217fb669225a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_conversation_tenant_user_temp', 'conversation', ['tenant_id', 'user_id'], unique=True, postgresql_where=sa.text('status = 4'))
    op.create_table('message',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_message_conv_seq')
    )
    op.create_index('index_message_conv_seq', 'message', ['conversation_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_message_conv_seq', table_name='message')
    op.drop_table('message')
    op.drop_index('uq_conversation_tenant_user_temp', table_name='conversation', postgresql_where=sa.text('status = 4'))
    op.drop_table('conversation')
    # ### end Alembic commands ###
