"""model provider add desc

Revision ID: 491e531177b1
Revises: 2964173cbe96
Create Date: 2025-07-15 11:26:45.817134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491e531177b1'
down_revision: Union[str, Sequence[str], None] = '2964173cbe96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_provider', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_provider', 'desc')
    # ### end Alembic commands ###
