"""all models add relationship

Revision ID: 525d80d35ee1
Revises: 6172c1a5d8ae
Create Date: 2025-07-22 17:05:59.882298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525d80d35ee1'
down_revision: Union[str, Sequence[str], None] = '6172c1a5d8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tenant_user_join', 'tenant', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tenant_user_join', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_user_join', type_='foreignkey')
    op.drop_constraint(None, 'tenant_user_join', type_='foreignkey')
    # ### end Alembic commands ###
