"""Docunment add chunk_type and size

Revision ID: 5472529ccf71
Revises: 87f18e926c3d
Create Date: 2025-11-23 22:06:41.933925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5472529ccf71"
down_revision: Union[str, Sequence[str], None] = "87f18e926c3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column(
            "chunk_type", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "document",
        sa.Column("size", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.add_column(
        "wiki",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wiki", "user_id")
    op.drop_column("document", "size")
    op.drop_column("document", "chunk_type")
    # ### end Alembic commands ###
