"""add Tenant

Revision ID: 557d885c4806
Revises: bfb7b69c378d
Create Date: 2025-07-22 13:05:15.381653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557d885c4806'
down_revision: Union[str, Sequence[str], None] = 'bfb7b69c378d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encrypt_public_key', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=255), server_default=sa.text("'basic'::character varying"), nullable=False),
    sa.Column('status', sa.String(length=255), server_default='unintialized', nullable=False),
    sa.Column('custom_config', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_user_join',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='tenant_user_join_pkey'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='unique_tenant_user_join')
    )
    op.create_index('tenant_user_join_account_id_idx', 'tenant_user_join', ['user_id'], unique=False)
    op.create_index('tenant_user_join_tenant_id_idx', 'tenant_user_join', ['tenant_id'], unique=False)
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'name')
    op.drop_index('tenant_user_join_tenant_id_idx', table_name='tenant_user_join')
    op.drop_index('tenant_user_join_account_id_idx', table_name='tenant_user_join')
    op.drop_table('tenant_user_join')
    op.drop_table('tenant')
    # ### end Alembic commands ###
