"""delete wiki user_id

Revision ID: 5a440c4379c5
Revises: 7c515b71add2
Create Date: 2025-08-10 17:37:59.219601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a440c4379c5'
down_revision: Union[str, Sequence[str], None] = '7c515b71add2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_user_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('wiki', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('tenant_user_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
