"""model provider add api key

Revision ID: 5e8447c2abed
Revises: b378284cf99e
Create Date: 2025-07-17 16:37:00.880523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8447c2abed'
down_revision: Union[str, Sequence[str], None] = 'b378284cf99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_provider', sa.Column('api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_provider', 'api_key')
    # ### end Alembic commands ###
