"""update User status Integer -> String

Revision ID: 6172c1a5d8ae
Revises: 31f33e04484c
Create Date: 2025-07-22 15:51:42.836934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6172c1a5d8ae'
down_revision: Union[str, Sequence[str], None] = '31f33e04484c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
