"""wiki add chunk_type

Revision ID: 6b206dac9ae3
Revises: 5472529ccf71
Create Date: 2025-11-30 21:11:57.347243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b206dac9ae3"
down_revision: Union[str, Sequence[str], None] = "5472529ccf71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wiki",
        sa.Column("chunk_type", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wiki", "chunk_type")
    # ### end Alembic commands ###
