"""document add relationship

Revision ID: 7426f57513d3
Revises: bfdb3c406827
Create Date: 2025-12-06 13:53:21.731362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7426f57513d3'
down_revision: Union[str, Sequence[str], None] = 'bfdb3c406827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'wiki_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'wiki_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
