"""update conversation message add thinking

Revision ID: 7554cfa72c1d
Revises: f8feaf3599d9
Create Date: 2025-11-06 18:22:22.805625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7554cfa72c1d'
down_revision: Union[str, Sequence[str], None] = 'f8feaf3599d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_tasks')
    op.add_column('message', sa.Column('thinking', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'thinking')
    op.create_table('conversation_tasks',
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_streaming', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_tasks_pkey'))
    )
    # ### end Alembic commands ###
