"""document delete wiki_id

Revision ID: 78a37e756f11
Revises: 0db008c8290a
Create Date: 2025-12-05 23:01:49.188985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a37e756f11'
down_revision: Union[str, Sequence[str], None] = '0db008c8290a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('index_document_wiki_id_status'), table_name='document')
    op.drop_constraint(op.f('document_wiki_id_fkey'), 'document', type_='foreignkey')
    op.drop_column('document', 'wiki_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('wiki_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('document_wiki_id_fkey'), 'document', 'wiki', ['wiki_id'], ['id'])
    op.create_index(op.f('index_document_wiki_id_status'), 'document', ['wiki_id', 'status'], unique=False)
    # ### end Alembic commands ###
