"""reset

Revision ID: 7c515b71add2
Revises: faab5e72d85b
Create Date: 2025-08-10 10:54:51.585522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c515b71add2'
down_revision: Union[str, Sequence[str], None] = 'faab5e72d85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('model_provider', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('model_provider_tenant_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tenant', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tenant_user_join', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tenant_user_join', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tenant_user_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('fk_tenant_user_join_user_id'), 'tenant_user_join', type_='foreignkey')
    op.drop_constraint(op.f('fk_tenant_user_join_tenant_id'), 'tenant_user_join', type_='foreignkey')
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('wiki', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wiki', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(op.f('fk_tenant_user_join_tenant_id'), 'tenant_user_join', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('fk_tenant_user_join_user_id'), 'tenant_user_join', 'user', ['user_id'], ['id'])
    op.alter_column('tenant_user_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tenant_user_join', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tenant_user_join', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tenant', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_provider_tenant_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_provider', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
