"""wiki add user_id

Revision ID: 87f18e926c3d
Revises: d68955bb0e42
Create Date: 2025-11-19 18:27:55.797703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f18e926c3d'
down_revision: Union[str, Sequence[str], None] = 'd68955bb0e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'user_id')
    # ### end Alembic commands ###
