"""cancel cascade

Revision ID: 9219c2768015
Revises: c610a38f91a6
Create Date: 2025-08-07 10:37:44.191771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9219c2768015'
down_revision: Union[str, Sequence[str], None] = 'c610a38f91a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('model_model_provider_id_fkey'), 'model', type_='foreignkey')
    op.create_foreign_key(None, 'model', 'model_provider', ['model_provider_id'], ['id'])
    op.drop_constraint(op.f('model_provider_tenant_join_tenant_id_fkey'), 'model_provider_tenant_join', type_='foreignkey')
    op.drop_constraint(op.f('model_provider_tenant_join_model_provider_id_fkey'), 'model_provider_tenant_join', type_='foreignkey')
    op.create_foreign_key(None, 'model_provider_tenant_join', 'model_provider', ['model_provider_id'], ['id'])
    op.create_foreign_key(None, 'model_provider_tenant_join', 'tenant', ['tenant_id'], ['id'])
    op.alter_column('tenant_user_join', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tenant_user_join', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('tenant_user_join_account_id_idx'), table_name='tenant_user_join')
    op.create_index('tenant_user_join_user_id_idx', 'tenant_user_join', ['user_id'], unique=False)
    op.drop_constraint(op.f('tenant_user_join_tenant_id_fkey'), 'tenant_user_join', type_='foreignkey')
    op.drop_constraint(op.f('tenant_user_join_user_id_fkey'), 'tenant_user_join', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_user_join', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'tenant_user_join', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_user_join', type_='foreignkey')
    op.drop_constraint(None, 'tenant_user_join', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_user_join_user_id_fkey'), 'tenant_user_join', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tenant_user_join_tenant_id_fkey'), 'tenant_user_join', 'tenant', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_index('tenant_user_join_user_id_idx', table_name='tenant_user_join')
    op.create_index(op.f('tenant_user_join_account_id_idx'), 'tenant_user_join', ['user_id'], unique=False)
    op.alter_column('tenant_user_join', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tenant_user_join', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'model_provider_tenant_join', type_='foreignkey')
    op.drop_constraint(None, 'model_provider_tenant_join', type_='foreignkey')
    op.create_foreign_key(op.f('model_provider_tenant_join_model_provider_id_fkey'), 'model_provider_tenant_join', 'model_provider', ['model_provider_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('model_provider_tenant_join_tenant_id_fkey'), 'model_provider_tenant_join', 'tenant', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.create_foreign_key(op.f('model_model_provider_id_fkey'), 'model', 'model_provider', ['model_provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
