"""delete model api key

Revision ID: b378284cf99e
Revises: a3aa1cf38616
Create Date: 2025-07-17 16:25:14.160939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b378284cf99e'
down_revision: Union[str, Sequence[str], None] = 'a3aa1cf38616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
