"""update enums type

Revision ID: b8e3cc02d08f
Revises: 7554cfa72c1d
Create Date: 2025-11-13 18:44:24.786887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e3cc02d08f'
down_revision: Union[str, Sequence[str], None] = '7554cfa72c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('tenant_user_join',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('role', sa.Integer(), server_default='normal', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tenant_user_join_pkey'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='unique_tenant_user_join')
    )
    op.create_index('tenant_user_join_tenant_id_idx', 'tenant_user_join', ['tenant_id'], unique=False)
    op.create_index('tenant_user_join_user_id_idx', 'tenant_user_join', ['user_id'], unique=False)
    op.drop_column('model', 'token_limit')
    op.alter_column('tenant', 'encrypt_public_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('wiki', 'sim_thresh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('sim_thresh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('tenant', 'encrypt_public_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('model', sa.Column('token_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('tenant_user_join_user_id_idx', table_name='tenant_user_join')
    op.drop_index('tenant_user_join_tenant_id_idx', table_name='tenant_user_join')
    op.drop_table('tenant_user_join')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
