"""update wiki model

Revision ID: c610a38f91a6
Revises: 8f4c9b2f9a8f
Create Date: 2025-08-06 17:58:19.346044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c610a38f91a6'
down_revision: Union[str, Sequence[str], None] = '8f4c9b2f9a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.alter_column('wiki', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('wiki_user_id_fkey'), 'wiki', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('wiki_user_id_fkey'), 'wiki', 'user', ['user_id'], ['id'])
    op.alter_column('wiki', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('wiki', 'tenant_id')
    # ### end Alembic commands ###
