"""add_document

Revision ID: cc3402c77354
Revises: eeae1ab7c5fc
Create Date: 2025-11-17 11:52:24.012140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc3402c77354'
down_revision: Union[str, Sequence[str], None] = 'eeae1ab7c5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('wiki_id', sa.UUID(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wiki_id'], ['wiki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_document_wiki_id_status', 'document', ['wiki_id', 'status'], unique=False)
    op.create_table('parent_chunk',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('wiki_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['wiki_id'], ['wiki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_parent_chunk_wiki_id', 'parent_chunk', ['wiki_id'], unique=False)
    op.create_index('index_parent_chunk_wiki_id_document_id', 'parent_chunk', ['wiki_id', 'document_id'], unique=False)
    op.create_table('child_chunk',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('wiki_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_chunk.id'], ),
    sa.ForeignKeyConstraint(['wiki_id'], ['wiki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_chunk')
    op.drop_index('index_parent_chunk_wiki_id_document_id', table_name='parent_chunk')
    op.drop_index('index_parent_chunk_wiki_id', table_name='parent_chunk')
    op.drop_table('parent_chunk')
    op.drop_index('index_document_wiki_id_status', table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
