"""update child chunk

Revision ID: e2338c2fb403
Revises: cc3402c77354
Create Date: 2025-11-17 19:33:59.660121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2338c2fb403'
down_revision: Union[str, Sequence[str], None] = 'cc3402c77354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_chunk', sa.Column('index_in_parent', sa.Integer(), nullable=False))
    op.add_column('child_chunk', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('child_chunk', sa.Column('embedding_status', sa.Integer(), nullable=False))
    op.add_column('child_chunk', sa.Column('vector_point_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_chunk', 'vector_point_id')
    op.drop_column('child_chunk', 'embedding_status')
    op.drop_column('child_chunk', 'content')
    op.drop_column('child_chunk', 'index_in_parent')
    # ### end Alembic commands ###
