"""add document index task

Revision ID: e88d9391a41a
Revises: e2338c2fb403
Create Date: 2025-11-18 11:50:40.415932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88d9391a41a'
down_revision: Union[str, Sequence[str], None] = 'e2338c2fb403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_index_task',
    sa.Column('wikiId', sa.UUID(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('processed_chunks', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wikiId'], ['wiki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_index_task')
    # ### end Alembic commands ###
