"""user model model_provider_id nullable=True

Revision ID: f1e1cb3aa881
Revises: 049d7454a58e
Create Date: 2025-07-23 22:53:37.674366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e1cb3aa881'
down_revision: Union[str, Sequence[str], None] = '049d7454a58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'model_provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'model_provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
