"""reset

Revision ID: faab5e72d85b
Revises: 
Create Date: 2025-08-10 10:15:32.710102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faab5e72d85b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_provider', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_provider_tenant_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('model_provider_tenant_join_model_provider_id_fkey'), 'model_provider_tenant_join', type_='foreignkey')
    op.drop_constraint(op.f('model_provider_tenant_join_tenant_id_fkey'), 'model_provider_tenant_join', type_='foreignkey')
    op.create_foreign_key(None, 'model_provider_tenant_join', 'model_provider', ['model_provider_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'model_provider_tenant_join', 'tenant', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tenant', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('tenant_user_join', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('tenant_user_join', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tenant_user_join', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'tenant_user_join', 'tenant', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tenant_user_join', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('wiki', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wiki', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'tenant_user_join', type_='foreignkey')
    op.drop_constraint(None, 'tenant_user_join', type_='foreignkey')
    op.drop_column('tenant_user_join', 'updated_at')
    op.drop_column('tenant_user_join', 'created_at')
    op.drop_column('tenant_user_join', 'active')
    op.alter_column('tenant', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'model_provider_tenant_join', type_='foreignkey')
    op.drop_constraint(None, 'model_provider_tenant_join', type_='foreignkey')
    op.create_foreign_key(op.f('model_provider_tenant_join_tenant_id_fkey'), 'model_provider_tenant_join', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('model_provider_tenant_join_model_provider_id_fkey'), 'model_provider_tenant_join', 'model_provider', ['model_provider_id'], ['id'])
    op.alter_column('model_provider_tenant_join', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('model_provider', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('model', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
