"""更新模型提供商的字段

Revision ID: ff39856360b0
Revises: 80f4cf88b889
Create Date: 2025-09-17 14:49:20.830186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff39856360b0'
down_revision: Union[str, Sequence[str], None] = '80f4cf88b889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_provider', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('model_provider', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_provider', 'display_name')
    op.drop_column('model_provider', 'logo')
    # ### end Alembic commands ###
